# Generated by rust2rpm 27
%bcond check 1

%global crate rioterm

Name:           rio
Version:        0.2.7
Release:        %autorelease
Summary:        Rio is a modern terminal built to run everywhere.

License:        MIT
URL:            https://crates.io/crates/rioterm
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          rio-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rio terminal is a hardware-accelerated GPU terminal emulator, focusing
to run in desktops and browsers.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

# 0BSD OR MIT OR Apache-2.0
# Apache-2.0
# Apache-2.0 OR MIT
# (Apache-2.0 OR MIT) AND BSD-3-Clause
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause
# BSD-2-Clause OR Apache-2.0 OR MIT
# BSD-3-Clause
# BSL-1.0
# CC0-1.0
# CC0-1.0 OR Apache-2.0 OR Apache-2.0 WITH LLVM-exception
# CC0-1.0 OR MIT-0 OR Apache-2.0
# ISC
# MIT
# MIT OR Apache-2.0
# (MIT OR Apache-2.0) AND Unicode-3.0
# MIT OR Apache-2.0 OR Zlib
# MIT OR Zlib OR Apache-2.0
# MPL-2.0
# MPL-2.0+
# MPL-2.0 OR GPL-3.0-only
# Unicode-3.0
# Unlicense OR MIT
# Zlib
# Zlib OR Apache-2.0 OR MIT
License:        0BSD AND Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND CC0-1.0 AND ISC AND MIT AND MIT-0 AND MPL-2.0 AND Unicode-3.0 AND Unlicense AND Zlib AND GPL-3.0-only
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
# FIXME: no license files detected
%license LICENSE.dependencies
%doc README.md
%{_bindir}/rio

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
